language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - jruby-19mode # JRuby in 1.9 mode
# uncomment this line if your project needs to run something other than `rake`:
script: rake test_specs
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtokyocabinet9 libtokyocabinet-dev 
