language: ruby
rvm:
  - 2.1.5
  - 2.2.3
  - rbx-2.5.8
  - jruby-19mode
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtokyocabinet-dev
# uncomment this line if your project needs to run something other than `rake`:
script: rake test_specs
